name: Tests

env:
  GOBIN: /tmp/bin
  TEST_RESULTS: /tmp/test-results

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Create temp directories
        run: mkdir -p $TEST_RESULTS

      - name: Install dependencies
        run: make install

      - name: Run tests
        run: |
          trap "$GOBIN/go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
          go test -cover -race -coverprofile=${TEST_RESULTS}/coverage.out -v ./... | tee ${TEST_RESULTS}/go-test.out
